language: php
php:
  - 5.6
  - 7.0
matrix:
    allow_failures:
      - php: 7.0
install:
 - composer self-update
 - composer install --no-interaction --dev
before_script:
 - mkdir -p build/
 - mkdir -p build/logs
script:
 - composer test
after_script:
 - php vendor/bin/coveralls -v
